### PR TITLE
Replace PRIMITIVE_COLORS with COLORS

### PR DESCRIPTION
**Pull request by ukorvl**
Replacement of PRIMITIVE_COLORS variable with COLORS to make it shorter and more convenient to use. Name primitive colors makes no since we have no "non-primitive" colors.

### CODE REVIEW

**Comment by KlonD90** [comment]
It's breaking changes

**Review by KlonD90 — CHANGES_REQUESTED** [review]
It should have 3.0 version because it's breaking changes or you should provide backward compatibility

**Comment by ukorvl** [comment]
> It should have 3.0 version because it's breaking changes or you should provide backward compatibility

Agree, thanks.

**Review by KlonD90 — APPROVED** [review]
LGTM

**Review by KlonD90 — APPROVED** [review]

**Pull request merged**
